# Generated by Django 3.0 on 2019-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question1', models.CharField(max_length=255)),
                ('response1', models.SmallIntegerField()),
                ('question2', models.CharField(max_length=255)),
                ('response2', models.SmallIntegerField()),
                ('question3', models.CharField(max_length=255)),
                ('response3', models.SmallIntegerField()),
                ('question4', models.CharField(max_length=255)),
                ('response4', models.SmallIntegerField()),
                ('question5', models.CharField(max_length=255)),
                ('response5', models.SmallIntegerField()),
            ],
        ),
    ]
