# Generated by Django 3.0 on 2019-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191211_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='title',
        ),
    ]
